-- 3 - Qual a capacidade da arena dos jogos com mais pontuação no banco de dados?

SELECT TEAM.ARENA_CAPACITY, TEAM.ARENA, GAME_DETAIL.POINTS
FROM GAME_DETAIL
INNER JOIN TEAM
ON TEAM.TEAM_ID = GAME_DETAIL.TEAM_ID
ORDER BY GAME_DETAIL.POINTS desc;

-- 9 - Quais os 5 piores HEADCOACHs em quantidade de pontos no banco de dados?

SELECT SUM(GAME_DETAIL.POINTS) AS PONTOS, TEAM.HEADCOACH
FROM GAME_DETAIL 
INNER JOIN TEAM
ON GAME_DETAIL.TEAM_ID = TEAM.team_id 
GROUP BY TEAM.HEADCOACH
ORDER BY PONTOS LIMIT 5;