-- 4 - Que jogadores possuem mais pontos na temporada de 2011?

SELECT PLAYER.NAME, SUM(GAME_DETAIL.POINTS) AS PONTOS
FROM GAME_DETAIL
INNER JOIN PLAYER
ON GAME_DETAIL.PLAYER_ID = PLAYER.PLAYER_ID
WHERE SEASON = 2011
GROUP BY PLAYER.PLAYER_ID
ORDER BY PONTOS DESC

-- 5 - Quais jogadores possui a maior quantidade de cestas de 3 pontos?

SELECT PLAYER.NAME, GAME_DETAIL.FG3
FROM GAME_DETAIL
INNER JOIN PLAYER
ON PLAYER.PLAYER_ID = GAME_DETAIL.PLAYER_ID
ORDER BY GAME_DETAIL.FG3 desc;